#!/bin/sh

#======================================================================
# this script fails in LIMA and PROCLIB if it is run as post-commit
#   .../Lima/.git/modules/camera/pco/hooks/post-commit
#
# problem related with the change to other directory during the 
#   git process??? 
#      (cd ../.. ;) (cd ../../third-party/Processlib ;)
#======================================================================

FILE="./include/PcoGitVersion.h"
LOG="./doc/VERSION.log"

DT=`date +"%Y/%m/%d %H:%M:%S"`

PCOREV=`git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`
LIMAREV=`cd ../.. ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`
PROCLIBREV=`cd ../../third-party/Processlib ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`
LIBCONFIGREV=`cd ../../third-party/libconfig ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`
TANGOREV=`cd ../../applications/tango ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`

{
echo "#define        PCO_GIT_VERSION \"\$Id:       PCO ${PCOREV} at [${DT}] \$\"" 
echo "#define       LIMA_GIT_VERSION \"\$Id:      LIMA ${LIMAREV} at [${DT}] \$\"" 
echo "#define    PROCLIB_GIT_VERSION \"\$Id:   PROCLIB ${PROCLIBREV} at [${DT}] \$\"" 
echo "#define  LIBCONFIG_GIT_VERSION \"\$Id: LIBCONFIG ${LIBCONFIGREV} at [${DT}] \$\"" 
echo "#define      TANGO_GIT_VERSION \"\$Id:     TANGO ${TANGOREV} at [${DT}] \$\"" 
} > ${FILE}

cat ${FILE}

{
echo
echo
date "+%Y/%m/%d %H:%M:%S =========================================="
cat ${FILE}
echo
echo
cat ${LOG}
} > ${LOG}.bck.bck
cp -f ${LOG} ${LOG}.bck
mv -f ${LOG}.bck.bck ${LOG}





